### ISSUE TITLE
Can't report errors within an eval statement

### ISSUE THREAD

**Issue by saiichihashimoto** [kogg/hovercards#188]
We need to rid ourselves of the few eval statements we have so that we can actually identify errors within them.

https://sentry.io/kogg/hovercards/issues/156483391/

```
TypeError: Cannot read property 'postMessage' of null
  at X.g.C (eval at <anonymous> (chrome-extension://dighmiipfpfdfbfmpodcmfdgkkcakbco/top-frame.js:2:11053), <anonymous>:98:351)
  at Array.forEach.d (eval at <anonymous> (chrome-extension://dighmiipfpfdfbfmpodcmfdgkkcakbco/top-frame.js:2:11053), <anonymous>:18:177)
  at Nb.W.g (eval at <anonymous> (chrome-extension://dighmiipfpfdfbfmpodcmfdgkkcakbco/top-frame.js:2:11053), <anonymous>:123:235)
  at f (eval at <anonymous> (chrome-extension://dighmiipfpfdfbfmpodcmfdgkkcakbco/top-frame.js:2:11053), <anonymous>:72:28)
  at apply (~/raven-js/src/raven.js:286:28)
```

**Comment by saiichihashimoto** [comment]
https://sentry.io/kogg/hovercards/issues/156538407/
